/*
 *  KernelEx
 *  Copyright (C) 2008, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "common.h"
#include "kexcoresdk.h"
#include "_ntdll_apilist.h"
#include "../kernel32/_kernel32_apilist.h"

BOOL init_ntdll()
{
	return TRUE;
}

static const apilib_named_api ntdll_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("NtCreateProcess", NtCreateProcess_stub),
	DECL_API("NtCreateThread", NtCreateThread_stub),
	DECL_API("NtGetContextThread", ZwGetContextThread),
	DECL_API("NtOpenProcess", ZwOpenProcess),
	DECL_API("NtOpenThread", ZwOpenThread),
	DECL_API("NtQuerySystemInformation", NtQuerySystemInformation_stub),
	DECL_API("NtResumeProcess", ZwResumeProcess),
	DECL_API("NtResumeThread", ZwResumeThread),
	DECL_API("NtSetContextThread", ZwSetContextThread),
	DECL_API("NtShutdownSystem", NtShutdownSystem_stub),
	DECL_API("NtSuspendProcess", ZwSuspendProcess),
	DECL_API("NtSuspendThread", ZwSuspendThread),
	DECL_API("NtTerminateProcess", ZwTerminateProcess),
	DECL_API("NtTerminateThread", ZwTerminateThread),
	DECL_API("ZwCreateProcess", ZwCreateProcess_stub),
	DECL_API("ZwCreateThread", ZwCreateThread_stub),
	DECL_API("ZwGetContextThread", ZwGetContextThread),
	DECL_API("ZwOpenProcess", ZwOpenProcess),
	DECL_API("ZwOpenThread", ZwOpenThread),
	DECL_API("ZwQuerySystemInformation", ZwQuerySystemInformation_stub),
	DECL_API("ZwResumeProcess", ZwResumeProcess),
	DECL_API("ZwResumeThread", ZwResumeThread),
	DECL_API("ZwSetContextThread", ZwSetContextThread),
	DECL_API("ZwShutdownSystem", ZwShutdownSystem_stub),
	DECL_API("ZwSuspendProcess", ZwSuspendProcess),
	DECL_API("ZwSuspendThread", ZwSuspendThread),
	DECL_API("ZwTerminateProcess", ZwTerminateProcess),
	DECL_API("ZwTerminateThread", ZwTerminateThread),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api ntdll_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_ntdll = DECL_TAB("NTDLL.DLL", ntdll_named_apis, 0 /*ntdll_ordinal_apis*/);
