/*
 *  KernelEx
 *  Copyright (C) 2013, Ley0k
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "_ntdll_apilist.h"
#include <strsafe.h>
#include "kexcoresdk.h"

DWORD __fastcall VKernelExCall(DWORD command, DWORD param1)
{
	BOOL result;
	DWORD retlen;
    HANDLE VKernelEx;
	CHAR lpkexDir[MAX_PATH];
	DWORD ret = 0 ;

	char vxdpath[MAX_PATH];

	kexGetKernelExDirectory(lpkexDir, sizeof(lpkexDir));

	StringCbPrintfA(vxdpath, sizeof(vxdpath), "\\\\.\\%sVKRNLEX.VXD", 
		(const char*) lpkexDir);

	VKernelEx = CreateFile(vxdpath, 0, 0, 0, 0, FILE_FLAG_DELETE_ON_CLOSE, 0);

	if (VKernelEx == INVALID_HANDLE_VALUE)
	{
		DBGPRINTF(("Failed to connect to VKernelEx!\n"));
		return false;
	}

	result = DeviceIoControl(VKernelEx, command, &param1, sizeof(DWORD), 
		&ret, sizeof(DWORD), &retlen, NULL);

	CloseHandle(VKernelEx);

	if (retlen > sizeof(DWORD))
		return false;

	return true;
}

BOOL init_ntdll()
{
	return TRUE;
}

static const apilib_named_api ntdll_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("LdrLoadDll", LdrLoadDll),
	DECL_API("LdrUnloadDll", LdrUnloadDll),
	DECL_API("NtAdjustPrivilegesToken", NtAdjustPrivilegesToken),
	DECL_API("NtAllocateVirtualMemory", NtAllocateVirtualMemory),
	DECL_API("NtClose", NtClose),
	DECL_API("NtCreateProcess", NtCreateProcess_stub),
	DECL_API("NtCreateSection", NtCreateSection),
	DECL_API("NtCreateThread", NtCreateThread),
	DECL_API("NtDuplicateObject", NtDuplicateObject),
	DECL_API("NtFreeVirtualMemory", NtFreeVirtualMemory),
	DECL_API("NtGetContextThread", NtGetContextThread),
	DECL_API("NtOpenFile", NtOpenFile),
	DECL_API("NtOpenProcess", NtOpenProcess),
	DECL_API("NtOpenProcessToken", NtOpenProcessToken),
	DECL_API("NtOpenThread", NtOpenThread),
	DECL_API("NtQuerySection", NtQuerySection),
	DECL_API("NtQuerySystemInformation", NtQuerySystemInformation),
	DECL_API("NtQuerySystemTime", NtQuerySystemTime),
	DECL_API("NtRaiseHardError", NtRaiseHardError),
	DECL_API("NtResumeProcess", NtResumeProcess),
	DECL_API("NtResumeThread", NtResumeThread),
	DECL_API("NtSetContextThread", NtSetContextThread),
	DECL_API("NtShutdownSystem", NtShutdownSystem),
	DECL_API("NtSuspendProcess", NtSuspendProcess),
	DECL_API("NtSuspendThread", NtSuspendThread),
	DECL_API("NtTerminateProcess", NtTerminateProcess),
	DECL_API("NtTerminateThread", NtTerminateThread),
	DECL_API("NtWaitForSingleObject", NtWaitForSingleObject),
	DECL_API("RtlDeleteCriticalSection", RtlDeleteCriticalSection),
	DECL_API("RtlEnterCriticalSection", RtlEnterCriticalSection),
	DECL_API("RtlGetVersion", RtlGetVersion),
	DECL_API("RtlInitAnsiString", RtlInitAnsiString),
	DECL_API("RtlInitAnsiStringEx", RtlInitAnsiStringEx),
	DECL_API("RtlInitializeCriticalSection", RtlInitializeCriticalSection),
	DECL_API("RtlInitializeCriticalSectionAndSpinCount", RtlInitializeCriticalSectionAndSpinCount),
	DECL_API("RtlInitializeCriticalSectionEx", RtlInitializeCriticalSectionEx),
	DECL_API("RtlLeaveCriticalSection", RtlLeaveCriticalSection),
	DECL_API("RtlNtStatusToDosError", RtlNtStatusToDosError),
	DECL_API("RtlTryEnterCriticalSection", RtlTryEnterCriticalSection),
	DECL_API("RtlVerifyVersionInfo", RtlVerifyVersionInfo),
	DECL_API("ZwAdjustPrivilegesToken", NtAdjustPrivilegesToken),
	DECL_API("ZwAllocateVirtualMemory", NtAllocateVirtualMemory),
	DECL_API("ZwClose", NtClose),
	DECL_API("ZwCreateProcess", ZwCreateProcess_stub),
	DECL_API("ZwCreateSection", NtCreateSection),
	DECL_API("ZwCreateThread", NtCreateThread),
	DECL_API("ZwDuplicateObject", NtDuplicateObject),
	DECL_API("ZwFreeVirtualMemory", NtFreeVirtualMemory),
	DECL_API("ZwGetContextThread", NtGetContextThread),
	DECL_API("ZwOpenFile", NtOpenFile),
	DECL_API("ZwOpenProcess", NtOpenProcess),
	DECL_API("ZwOpenProcessToken", NtOpenProcessToken),
	DECL_API("ZwOpenThread", NtOpenThread),
	DECL_API("ZwQuerySection", NtQuerySection),
	DECL_API("ZwQuerySystemInformation", NtQuerySystemInformation),
	DECL_API("ZwQuerySystemTime", NtQuerySystemTime),
	DECL_API("ZwRaiseHardError", NtRaiseHardError),
	DECL_API("ZwResumeProcess", NtResumeProcess),
	DECL_API("ZwResumeThread", NtResumeThread),
	DECL_API("ZwSetContextThread", NtSetContextThread),
	DECL_API("ZwShutdownSystem", NtShutdownSystem),
	DECL_API("ZwSuspendProcess", NtSuspendProcess),
	DECL_API("ZwSuspendThread", NtSuspendThread),
	DECL_API("ZwTerminateProcess", NtTerminateProcess),
	DECL_API("ZwTerminateThread", NtTerminateThread),
	DECL_API("ZwWaitForSingleObject", NtWaitForSingleObject),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api ntdll_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_ntdll = DECL_TAB("NTDLL.DLL", ntdll_named_apis, 0 /*ntdll_ordinal_apis*/);
