/*
 *  KernelEx
 *  Copyright (C) 2013, Ley0k
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "_ntdll_apilist.h"
#include <strsafe.h>
#include "kexcoresdk.h"

DWORD __fastcall VKernelExCall(DWORD command, DWORD param1)
{
	BOOL result;
	DWORD retlen;
    HANDLE VKernelEx;
	CHAR lpkexDir[MAX_PATH];
	DWORD ret = 0 ;

	char vxdpath[MAX_PATH];

	kexGetKernelExDirectory(lpkexDir, sizeof(lpkexDir));

	StringCbPrintfA(vxdpath, sizeof(vxdpath), "\\\\.\\%sVKRNLEX.VXD", 
		(const char*) lpkexDir);

	VKernelEx = CreateFile(vxdpath, 0, 0, 0, 0, FILE_FLAG_DELETE_ON_CLOSE, 0);

	if (VKernelEx == INVALID_HANDLE_VALUE)
	{
		DBGPRINTF(("Failed to connect to VKernelEx!\n"));
		return false;
	}

	result = DeviceIoControl(VKernelEx, command, &param1, sizeof(DWORD), 
		&ret, sizeof(DWORD), &retlen, NULL);

	CloseHandle(VKernelEx);

	if (retlen > sizeof(DWORD))
		return false;

	return true;
}

BOOL init_ntdll()
{
	return TRUE;
}

static const apilib_named_api ntdll_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("LdrLoadDll", LdrLoadDll),
	DECL_API("LdrUnloadDll", LdrUnloadDll),
	DECL_API("NtAdjustPrivilegesToken", NtAdjustPrivilegesToken),
	DECL_API("NtAllocateVirtualMemory", NtAllocateVirtualMemory),
	DECL_API("NtClose", NtClose),
	DECL_API("NtCreateEvent", NtCreateEvent),
	DECL_API("NtCreateProcess", NtCreateProcess_stub),
	DECL_API("NtCreateSection", NtCreateSection),
	DECL_API("NtCreateThread", NtCreateThread),
	DECL_API("NtDeviceIoControlFile", NtDeviceIoControlFile),
	DECL_API("NtDisplayString", NtDisplayString),
	DECL_API("NtDuplicateObject", NtDuplicateObject),
	DECL_API("NtFreeVirtualMemory", NtFreeVirtualMemory),
	DECL_API("NtFsControlFile", NtFsControlFile_stub),
	DECL_API("NtGetContextThread", NtGetContextThread),
	DECL_API("NtOpenDirectoryObject", NtOpenDirectoryObject_stub),
	DECL_API("NtOpenFile", NtOpenFile),
	DECL_API("NtOpenKey", NtOpenKey),
	DECL_API("NtOpenProcess", NtOpenProcess),
	DECL_API("NtOpenProcessToken", NtOpenProcessToken),
	DECL_API("NtOpenSymbolicLinkObject", NtOpenSymbolicLinkObject_stub),
	DECL_API("NtOpenThread", NtOpenThread),
	DECL_API("NtQueryDirectoryObject", NtQueryDirectoryObject_stub),
	DECL_API("NtQueryInformationFile", NtQueryInformationFile_stub),
	DECL_API("NtQuerySection", NtQuerySection),
	DECL_API("NtQuerySymbolicLinkObject", NtQuerySymbolicLinkObject_stub),
	DECL_API("NtQuerySystemInformation", NtQuerySystemInformation),
	DECL_API("NtQuerySystemTime", NtQuerySystemTime),
	DECL_API("NtQueryValueKey", NtQueryValueKey),
	DECL_API("NtRaiseHardError", NtRaiseHardError),
	DECL_API("NtReadFile", NtReadFile),
	DECL_API("NtResumeProcess", NtResumeProcess),
	DECL_API("NtResumeThread", NtResumeThread),
	DECL_API("NtSetContextThread", NtSetContextThread),
	DECL_API("NtSetEvent", NtSetEvent),
	DECL_API("NtSetInformationFile", NtSetInformationFile_stub),
	DECL_API("NtShutdownSystem", NtShutdownSystem),
	DECL_API("NtSuspendProcess", NtSuspendProcess),
	DECL_API("NtSuspendThread", NtSuspendThread),
	DECL_API("NtTerminateProcess", NtTerminateProcess),
	DECL_API("NtTerminateThread", NtTerminateThread),
	DECL_API("NtWaitForSingleObject", NtWaitForSingleObject),
	DECL_API("NtWriteFile", NtWriteFile),
	DECL_API("RtlAddAccessAllowedAce", RtlAddAccessAllowedAce_stub),
	DECL_API("RtlAddAce", RtlAddAce_stub),
	DECL_API("RtlClearBits", RtlClearBits_stub),
	DECL_API("RtlCompareUnicodeString", RtlCompareUnicodeString),
	DECL_API("RtlCopySid", RtlCopySid),
	DECL_API("RtlCreateAcl", RtlCreateAcl_stub),
	DECL_API("RtlCreateSecurityDescriptor", RtlCreateSecurityDescriptor),
	DECL_API("RtlDecompressBuffer", RtlDecompressBuffer_stub),
	DECL_API("RtlDeleteCriticalSection", RtlDeleteCriticalSection),
	DECL_API("RtlDeleteElementGenericTable", RtlDeleteElementGenericTable_stub),
	DECL_API("RtlDosPathNameToNtPathName_U", RtlDosPathNameToNtPathName_U),
	DECL_API("RtlEnterCriticalSection", RtlEnterCriticalSection),
	DECL_API("RtlEnumerateGenericTableWithoutSplaying", RtlEnumerateGenericTableWithoutSplaying_stub),
	DECL_API("RtlEqualUnicodeString", RtlEqualUnicodeString),
	DECL_API("RtlExpandEnvironmentStrings_U", RtlExpandEnvironmentStrings_U),
	DECL_API("RtlFindMessage", RtlFindMessage_stub),
	DECL_API("RtlFindSetBits", RtlFindSetBits_stub),
	DECL_API("RtlFormatMessage", RtlFormatMessage_stub),
	DECL_API("RtlFreeOemString", RtlFreeOemString),
	DECL_API("RtlFreeSid", RtlFreeSid),
	DECL_API("RtlFreeUnicodeString", RtlFreeUnicodeString),
	DECL_API("RtlGetVersion", RtlGetVersion),
	DECL_API("RtlInitAnsiString", RtlInitAnsiString),
	DECL_API("RtlInitAnsiStringEx", RtlInitAnsiStringEx),
	DECL_API("RtlInitUnicodeString", RtlInitUnicodeString),
	DECL_API("RtlInitializeBitMap", RtlInitializeBitMap),
	DECL_API("RtlInitializeCriticalSection", RtlInitializeCriticalSection),
	DECL_API("RtlInitializeCriticalSectionAndSpinCount", RtlInitializeCriticalSectionAndSpinCount),
	DECL_API("RtlInitializeCriticalSectionEx", RtlInitializeCriticalSectionEx),
	DECL_API("RtlInitializeGenericTable", RtlInitializeGenericTable_stub),
	DECL_API("RtlInitializeSid", RtlInitializeSid),
	DECL_API("RtlInsertElementGenericTable", RtlInsertElementGenericTable_stub),
	DECL_API("RtlLeaveCriticalSection", RtlLeaveCriticalSection),
	DECL_API("RtlLengthRequiredSid", RtlLengthRequiredSid),
	DECL_API("RtlLengthSecurityDescriptor", RtlLengthSecurityDescriptor_stub),
	DECL_API("RtlLengthSid", RtlLengthSid),
	DECL_API("RtlLookupElementGenericTable", RtlLookupElementGenericTable_stub),
	DECL_API("RtlNewSecurityObject", RtlNewSecurityObject_stub),
	DECL_API("RtlNormalizeProcessParams", RtlNormalizeProcessParams_stub),
	DECL_API("RtlNtStatusToDosError", RtlNtStatusToDosError),
	DECL_API("RtlNumberOfSetBits", RtlNumberOfSetBits_stub),
	DECL_API("RtlOemToUnicodeN", RtlOemToUnicodeN),
	DECL_API("RtlPrefixUnicodeString", RtlPrefixUnicodeString),
	DECL_API("RtlQueryInformationAcl", RtlQueryInformationAcl_stub),
	DECL_API("RtlQueryRegistryValues", RtlQueryRegistryValues_stub),
	DECL_API("RtlRaiseStatus", RtlRaiseStatus),
	DECL_API("RtlSetBits", RtlSetBits_stub),
	DECL_API("RtlSetDaclSecurityDescriptor", RtlSetDaclSecurityDescriptor_stub),
	DECL_API("RtlSetGroupSecurityDescriptor", RtlSetGroupSecurityDescriptor_stub),
	DECL_API("RtlSetOwnerSecurityDescriptor", RtlSetOwnerSecurityDescriptor_stub),
	DECL_API("RtlSubAuthoritySid", RtlSubAuthoritySid),
	DECL_API("RtlSystemTimeToLocalTime", RtlSystemTimeToLocalTime),
	DECL_API("RtlTimeToTimeFields", RtlTimeToTimeFields_stub),
	DECL_API("RtlTryEnterCriticalSection", RtlTryEnterCriticalSection),
	DECL_API("RtlUnicodeStringToOemString", RtlUnicodeStringToOemString),
	DECL_API("RtlUnicodeToOemN", RtlUnicodeToOemN),
	DECL_API("RtlUpcaseUnicodeChar", RtlUpcaseUnicodeChar),
	DECL_API("RtlUpcaseUnicodeString", RtlUpcaseUnicodeString),
	DECL_API("RtlValidSecurityDescriptor", RtlValidSecurityDescriptor_stub),
	DECL_API("RtlVerifyVersionInfo", RtlVerifyVersionInfo),
	DECL_API("RtlWriteRegistryValue", RtlWriteRegistryValue_stub),
	DECL_API("ZwAdjustPrivilegesToken", NtAdjustPrivilegesToken),
	DECL_API("ZwAllocateVirtualMemory", NtAllocateVirtualMemory),
	DECL_API("ZwClose", NtClose),
	DECL_API("ZwCreateEvent", NtCreateEvent),
	DECL_API("ZwCreateProcess", ZwCreateProcess_stub),
	DECL_API("ZwCreateSection", NtCreateSection),
	DECL_API("ZwCreateThread", NtCreateThread),
	DECL_API("ZwDeviceIoControlFile", NtDeviceIoControlFile),
	DECL_API("ZwDisplayString", NtDisplayString),
	DECL_API("ZwDuplicateObject", NtDuplicateObject),
	DECL_API("ZwFreeVirtualMemory", NtFreeVirtualMemory),
	DECL_API("ZwFsControlFile", ZwFsControlFile_stub),
	DECL_API("ZwGetContextThread", NtGetContextThread),
	DECL_API("ZwOpenDirectoryObject", ZwOpenDirectoryObject_stub),
	DECL_API("ZwOpenFile", NtOpenFile),
	DECL_API("ZwOpenKey", NtOpenKey),
	DECL_API("ZwOpenProcess", NtOpenProcess),
	DECL_API("ZwOpenProcessToken", NtOpenProcessToken),
	DECL_API("ZwOpenSymbolicLinkObject", ZwOpenSymbolicLinkObject_stub),
	DECL_API("ZwOpenThread", NtOpenThread),
	DECL_API("ZwQueryDirectoryObject", ZwQueryDirectoryObject_stub),
	DECL_API("ZwQueryInformationFile", ZwQueryInformationFile_stub),
	DECL_API("ZwQuerySection", NtQuerySection),
	DECL_API("ZwQuerySymbolicLinkObject", ZwQuerySymbolicLinkObject_stub),
	DECL_API("ZwQuerySystemInformation", NtQuerySystemInformation),
	DECL_API("ZwQuerySystemTime", NtQuerySystemTime),
	DECL_API("ZwQueryValueKey", NtQueryValueKey),
	DECL_API("ZwRaiseHardError", NtRaiseHardError),
	DECL_API("ZwReadFile", NtReadFile),
	DECL_API("ZwResumeProcess", NtResumeProcess),
	DECL_API("ZwResumeThread", NtResumeThread),
	DECL_API("ZwSetContextThread", NtSetContextThread),
	DECL_API("ZwSetEvent", NtSetEvent),
	DECL_API("ZwSetInformationFile", ZwSetInformationFile_stub),
	DECL_API("ZwShutdownSystem", NtShutdownSystem),
	DECL_API("ZwSuspendProcess", NtSuspendProcess),
	DECL_API("ZwSuspendThread", NtSuspendThread),
	DECL_API("ZwTerminateProcess", NtTerminateProcess),
	DECL_API("ZwTerminateThread", NtTerminateThread),
	DECL_API("ZwWaitForSingleObject", NtWaitForSingleObject),
	DECL_API("ZwWriteFile", NtWriteFile),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api ntdll_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_ntdll = DECL_TAB("NTDLL.DLL", ntdll_named_apis, 0 /*ntdll_ordinal_apis*/);
