/*
 *  KernelEx
 *  Copyright (C) 2008, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "common.h"
#include "kexcoresdk.h"
#include "_user32_apilist.h"

BOOL init_user32()
{
	return TRUE;
}

static const apilib_named_api user32_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("BroadcastSystemMessageW", BroadcastSystemMessageW_new),
	DECL_API("ChangeDisplaySettingsExW", ChangeDisplaySettingsExW_new),
	DECL_API("ChangeDisplaySettingsExW", ChangeDisplaySettingsExW_new),
	DECL_API("DdeCreateStringHandleW", DdeCreateStringHandleW_new),
	DECL_API("DdeInitializeW", DdeInitializeW_new),
	DECL_API("DdeQueryStringW", DdeQueryStringW_new),
	DECL_API("DlgDirListComboBoxW", DlgDirListComboBoxW_new),
	DECL_API("DlgDirListW", DlgDirListW_new),
	DECL_API("DlgDirSelectComboBoxExW", DlgDirSelectComboBoxExW_new),
	DECL_API("DlgDirSelectExW", DlgDirSelectExW_new),
	DECL_API("DrawStateW", DrawStateW_new),
	DECL_API("DrawTextExW", DrawTextExW_new),
	DECL_API("DrawTextW", DrawTextW_new),
	DECL_API("EnumDisplayDevicesW", EnumDisplayDevicesW_fwd),
	DECL_API("EnumDisplaySettingsExW", EnumDisplaySettingsExW_fwd),
	DECL_API("EnumDisplaySettingsW", EnumDisplaySettingsW_fwd),
	DECL_API("EnumPropsExW", EnumPropsExW_fwd),
	DECL_API("EnumPropsW", EnumPropsW_fwd),
	DECL_API("FindWindowExW", FindWindowExW_new),
	DECL_API("FindWindowW", FindWindowW_new),
	DECL_API("GetClassNameW", GetClassNameW_new),
	DECL_API("GetClipboardFormatNameW", GetClipboardFormatNameW_new),
	DECL_API("GetKeyNameTextW", GetKeyNameTextW_new),
	DECL_API("GetKeyboardLayoutNameW", GetKeyboardLayoutNameW_new),
	DECL_API("GetMenuItemInfoW", GetMenuItemInfoW_new),
	DECL_API("GetMenuStringW", GetMenuStringW_new),
	DECL_API("GetMonitorInfoW", GetMonitorInfoW_new),
	DECL_API("GetPropW", GetPropW_new),
	DECL_API("GetTabbedTextExtentW", GetTabbedTextExtentW_new),
	DECL_API("GrayStringW", GrayStringW_new),
	DECL_API("InsertMenuItemW", InsertMenuItemW_new),
	DECL_API("LoadAcceleratorsW_new", LoadAcceleratorsW_new),
	DECL_API("LoadBitmapW", LoadBitmapW_new),
	DECL_API("LoadCursorFromFileW", LoadCursorFromFileW_new),
	DECL_API("LoadCursorW", LoadCursorW_new),
	DECL_API("LoadIconW", LoadIconW_new),
	DECL_API("LoadImageW", LoadImageW_new),
	DECL_API("LoadKeyboardLayoutW", LoadKeyboardLayoutW_new),
	DECL_API("MapVirtualKeyExW", MapVirtualKeyExW_new),
	DECL_API("MapVirtualKeyW", MapVirtualKeyW_new),
	DECL_API("MessageBoxIndirectW", MessageBoxIndirectW_new),
	DECL_API("RegisterClipboardFormatW", RegisterClipboardFormatW_new),
	DECL_API("RegisterDeviceNotificationW", RegisterDeviceNotificationW_new),
	DECL_API("RegisterWindowMessageW_new", RegisterWindowMessageW_new),
	DECL_API("RemovePropW", RemovePropW_new),
	DECL_API("SetMenuItemInfoW", SetMenuItemInfoW_new),
	DECL_API("SetPropW", SetPropW_new),
	DECL_API("SystemParametersInfoW", SystemParametersInfoW_new),
	DECL_API("TabbedTextOutW", TabbedTextOutW_new),
	DECL_API("VkKeyScanExW", VkKeyScanExW_new),
	DECL_API("VkKeyScanW", VkKeyScanW_new),
	DECL_API("WinHelpW", WinHelpW_new),
	DECL_API("wsprintfW", wsprintfW_new),
	DECL_API("wvsprintfW", wvsprintfW_new),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api user32_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_user32 = DECL_TAB("USER32.DLL", user32_named_apis, 0 /*user32_ordinal_apis*/);
