/*
 *  KernelEx
 *  Copyright (C) 2009, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifndef _WINSPOOL_APILIST_H
#define _WINSPOOL_APILIST_H

#include "kexcoresdk.h"

BOOL init_winspool();
extern const apilib_api_table apitable_winspool;

/*** AUTOGENERATED APILIST DECLARATIONS BEGIN ***/
BOOL WINAPI GetDefaultPrinterA_new(LPSTR buf, LPDWORD size);
BOOL WINAPI GetDefaultPrinterW_new(LPWSTR bufW, LPDWORD sizeW);
STUB GetPrinterDataExA_stub;
STUB GetPrinterDataExW_stub;
STUB SetPrinterDataExA_stub;
STUB SetPrinterDataExW_stub;
FWDPROC AddJobW_fwd;
FWDPROC AddMonitorW_fwd;
FWDPROC AddPortW_fwd;
FWDPROC AddPrinterDriverW_fwd;
FWDPROC AddPrinterW_fwd;
FWDPROC AddPrintProcessorW_fwd;
FWDPROC AddPrintProvidorW_fwd;
FWDPROC AdvancedDocumentPropertiesW_fwd;
FWDPROC ConfigurePortW_fwd;
FWDPROC DeleteMonitorW_fwd;
FWDPROC DeletePortW_fwd;
FWDPROC DeletePrinterDriverW_fwd;
FWDPROC DeletePrintProcessorW_fwd;
FWDPROC DeletePrintProvidorW_fwd;
FWDPROC DeviceCapabilitiesW_fwd;
FWDPROC DocumentPropertiesW_fwd;
FWDPROC GetPrinterDriverDirectoryW_fwd;
FWDPROC GetPrintProcessorDirectoryW_fwd;
FWDPROC OpenPrinterW_fwd;
FWDPROC ResetPrinterW_fwd;
FWDPROC SetJobW_fwd;
FWDPROC SetPrinterDataW_fwd;
FWDPROC SetPrinterW_fwd;
FWDPROC StartDocPrinterW_fwd;
BOOL WINAPI EnumPrintersW_new(DWORD Flags, LPWSTR NameW, DWORD Level, LPBYTE pPrinterEnumW, DWORD cbBuf, LPDWORD pcbNeeded, LPDWORD pcReturned);
/*** AUTOGENERATED APILIST DECLARATIONS END ***/

#endif
