/*
 *  KernelEx
 *  Copyright (C) 2008, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifndef _ADVAPI32_APILIST_H
#define _ADVAPI32_APILIST_H

#include "kexcoresdk.h"

BOOL init_advapi32();
extern const apilib_api_table apitable_advapi32;

/*** AUTOGENERATED APILIST DECLARATIONS BEGIN ***/
FWDPROC GetUserNameW_fwd;
FWDPROC IsTextUnicode_fwd;
FWDPROC RegConnectRegistryW_fwd;
FWDPROC RegDeleteValueW_fwd;
FWDPROC RegEnumKeyExW_fwd;
FWDPROC RegEnumKeyW_fwd;
FWDPROC RegLoadKeyW_fwd;
FWDPROC RegQueryInfoKeyW_fwd;
FWDPROC RegQueryMultipleValuesW_fwd;
FWDPROC RegQueryValueW_fwd;
FWDPROC RegReplaceKeyW_fwd;
FWDPROC RegSaveKeyW_fwd;
FWDPROC RegSetValueW_fwd;
FWDPROC RegUnLoadKeyW_fwd;
/*** AUTOGENERATED APILIST DECLARATIONS END ***/

#endif
