/*
 *  KernelEx
 *  Copyright (C) 2013, Ley0k
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "_ntdll_apilist.h"

const unsigned char __ctypes[1] = { 0 }; // HACKHACK

BOOL init_ntdll()
{
	return TRUE;
}

void main(){}

static const apilib_named_api ntdll_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("_atoi64", _atoi64),
	DECL_API("_itoa", _itoa),
	DECL_API("_itow", _itow),
	DECL_API("_ltoa", _ltoa),
	DECL_API("_ltow", _ltow),
	DECL_API("_memccpy", _memccpy),
	DECL_API("_memicmp", _memicmp),
	DECL_API("_snprintf", _snprintf),
	DECL_API("_snwprintf", _snwprintf),
	DECL_API("_splitpath", _splitpath),
	DECL_API("_strcmpi", _strcmpi),
	DECL_API("_stricmp", _strnicmp),
	DECL_API("_strlwr", _strlwr),
	DECL_API("_strupr", _strupr),
	DECL_API("_tolower", __ctype_tolower),
	DECL_API("_toupper", __ctype_toupper),
	DECL_API("_ultoa", _ultoa),
	DECL_API("_ultow", _ultow),
	DECL_API("_vsnprintf", _vsnprintf),
	DECL_API("_wcsicmp", _wcsicmp),
	DECL_API("_wcslwr", _wcslwr),
	DECL_API("_wcsnicmp", _wcsnicmp),
	DECL_API("_wcsupr", _wcsupr),
	DECL_API("_wtoi", _wtoi),
	DECL_API("_wtoi64", _wtoi64),
	DECL_API("_wtol", _wtol),
	DECL_API("abs", abs),
	DECL_API("atan", atan),
	DECL_API("ceil", ceil),
	DECL_API("cos", cos),
	DECL_API("fabs", fabs),
	DECL_API("floor", floor),
	DECL_API("isalnum", __ctype_isalnum),
	DECL_API("isalpha", __ctype_isalpha),
	DECL_API("isascii", __ctype_isascii),
	DECL_API("iscntrl", __ctype_iscntrl),
	DECL_API("isdigit", __ctype_isdigit),
	DECL_API("isgraph", __ctype_isgraph),
	DECL_API("islower", __ctype_islower),
	DECL_API("ispunct", __ctype_ispunct),
	DECL_API("isspace", __ctype_isspace),
	DECL_API("isupper", __ctype_isupper),
	DECL_API("isxdigit", __ctype_isxdigit),
	DECL_API("labs", labs),
	DECL_API("log", log),
	DECL_API("mbstowcs", mbstowcs),
	DECL_API("memccpy", memccpy),
	DECL_API("memchr", memchr),
	DECL_API("memcmp", memcmp),
	DECL_API("memcpy", memcpy),
	DECL_API("memmove", memmove),
	DECL_API("memset", memset),
	DECL_API("pow", pow),
	DECL_API("qsort", qsort),
	DECL_API("sin", sin),
	DECL_API("sprintf", sprintf),
	DECL_API("sqrt", sqrt),
	DECL_API("sscanf", sscanf),
	DECL_API("strcat", strcat),
	DECL_API("strchr", strchr),
	DECL_API("strcmp", strcmp),
	DECL_API("strcmpi", strcmpi),
	DECL_API("strcpy", strcpy),
	DECL_API("strcspn", strcspn),
	DECL_API("strdup", strdup),
	DECL_API("strlen", strlen),
	DECL_API("strncat", strncat),
	DECL_API("strncmp", strncmp),
	DECL_API("strncpy", strncpy),
	DECL_API("strnicmp", strnicmp),
	DECL_API("strok", strtok),
	DECL_API("strpbrk", strpbrk),
	DECL_API("strrchr", strrchr),
	DECL_API("strstr", strstr),
	DECL_API("strtol", strtol),
	DECL_API("strtoul", strtoul),
	DECL_API("strupr", strupr),
	DECL_API("swprintf", swprintf),
	DECL_API("tan", tan),
	DECL_API("tolower", __ctype_tolower),
	DECL_API("toupper", __ctype_toupper),
	DECL_API("towlower", towlower),
	DECL_API("towupper", towupper),
	DECL_API("vsprintf", vsprintf),
	DECL_API("wcscat", wcscat),
	DECL_API("wcschr", wcschr),
	DECL_API("wcscmp", wcscmp),
	DECL_API("wcscpy", wcscpy),
	DECL_API("wcscspn", wcscspn),
	DECL_API("wcslen", wcslen),
	DECL_API("wcsncat", wcsncat),
	DECL_API("wcsncmp", wcsncmp),
	DECL_API("wcsncpy", wcsncpy),
	DECL_API("wcspbrk", wcspbrk),
	DECL_API("wcsrchr", wcsrchr),
	DECL_API("wcsspn", wcsspn),
	DECL_API("wcsstr", wcsstr),
	DECL_API("wcstol", wcstol),
	DECL_API("wcstombs", wcstombs),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api ntdll_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_ntdll = DECL_TAB("NTDLL.DLL", ntdll_named_apis, 0 /*ntdll_ordinal_apis*/);
