/*
 *  KernelEx
 *  Copyright (C) 2008, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#include "common.h"
#include "kexcoresdk.h"
#include "_kernel32_apilist.h"

extern BOOL init_threadpool();
extern BOOL init_jemalloc();
extern BOOL init_exttls();
extern void detach_exttls();

BOOL init_kernel32()
{
	return init_exttls() && init_threadpool() && init_jemalloc();
}

void uninit_kernel32()
{
}

void detach_kernel32()
{
	detach_exttls();
}

static const apilib_named_api kernel32_named_apis[] = 
{
/*** AUTOGENERATED APILIST NAMED EXPORTS BEGIN ***/
	DECL_API("BuildCommDCBAndTimeoutsW", BuildCommDCBAndTimeoutsW_new),
	DECL_API("BuildCommDCBW", BuildCommDCBW_new),
	DECL_API("CallNamedPipeW", CallNamedPipeW_new),
	DECL_API("CancelTimerQueueTimer", CancelTimerQueueTimer_new),
	DECL_API("ChangeTimerQueueTimer", ChangeTimerQueueTimer_new),
	DECL_API("CommConfigDialogW", CommConfigDialogW_new),
	DECL_API("CreateEventW", CreateEventW_new),
	DECL_API("CreateFileMapping", CreateFileMappingW_new),
	DECL_API("CreateMailslotW", CreateMailslotW_new),
	DECL_API("CreateMutexW", CreateMutexW_new),
	DECL_API("CreateSemaphoreW", CreateSemaphoreW_new),
	DECL_API("CreateTimerQueue", CreateTimerQueue_new),
	DECL_API("CreateTimerQueueTimer", CreateTimerQueueTimer_new),
	DECL_API("CreateWaitableTimerW", CreateWaitableTimerW_new),
	DECL_API("DelayLoadFailureHook", DelayLoadFailureHook_new),
	DECL_API("DeleteTimerQueue", DeleteTimerQueue_new),
	DECL_API("DeleteTimerQueueEx", DeleteTimerQueueEx_new),
	DECL_API("DeleteTimerQueueTimer", DeleteTimerQueueTimer_new),
	DECL_API("EnumCalendarInfoExW", EnumCalendarInfoExW_new),
	DECL_API("EnumCalendarInfoW", EnumCalendarInfoW_new),
	DECL_API("EnumDateFormatsExW", EnumDateFormatsExW_new),
	DECL_API("EnumDateFormatsW", EnumDateFormatsW_new),
	DECL_API("EnumSystemCodePagesW", EnumSystemCodePagesW_new),
	DECL_API("EnumSystemLocalesW", EnumSystemLocalesW_new),
	DECL_API("EnumTimeFormatsW", EnumTimeFormatsW_new),
	DECL_API("ExpandEnvironmentStringsW", ExpandEnvironmentStringsW_new),
	DECL_API("FatalAppExitW", FatalAppExitW_new),
	DECL_API("FillConsoleOutputCharacterW", FillConsoleOutputCharacterW_new),
	DECL_API("FormatMessageW", FormatMessageW_new),
	DECL_API("GetCPInfoExW", GetCPInfoExW_new),
	DECL_API("GetCalendarInfoW", GetCalendarInfoW_new),
	DECL_API("GetComputerNameW", GetComputerNameW_new),
	DECL_API("GetConsoleTitleW", GetConsoleTitleW_new),
	DECL_API("GetCurrencyFormatW", GetCurrencyFormatW_new),
	DECL_API("GetDateFormatW", GetDateFormatW_new),
	DECL_API("GetDriveTypeW", GetDriveTypeW_new),
	DECL_API("GetEnvironmentVariableW", GetEnvironmentVariableW_new),
	DECL_API("GetLogicalDriveStringsW", GetLogicalDriveStringsW_new),
	DECL_API("GetNamedPipeHandleStateW", GetNamedPipeHandleStateW_new),
	DECL_API("GetNumberFormatW", GetNumberFormatW_new),
	DECL_API("GetPrivateProfileIntW", GetPrivateProfileIntW_new),
	DECL_API("GetPrivateProfileSectionNamesW", GetPrivateProfileSectionNamesW_new),
	DECL_API("GetPrivateProfileSectionW", GetPrivateProfileSectionW_new),
	DECL_API("GetPrivateProfileStringW", GetPrivateProfileStringW_new),
	DECL_API("GetPrivateProfileStructW", GetPrivateProfileStructW_new),
	DECL_API("GetProfileIntW", GetProfileIntW_new),
	DECL_API("GetProfileSectionW", GetProfileSectionW_new),
	DECL_API("GetProfileStringW", GetProfileStringW_new),
	DECL_API("GetTimeFormatW", GetTimeFormatW_new),
	DECL_API("GetVolumeInformationW", GetVolumeInformationW_new),
	DECL_API("IsBadStringPtrW", IsBadStringPtrW_new),
	DECL_API("QueueUserWorkItem", QueueUserWorkItem_new),
	DECL_API("RegisterWaitForSingleObject", RegisterWaitForSingleObject_new),
	DECL_API("RegisterWaitForSingleObjectEx", RegisterWaitForSingleObjectEx_new),
	DECL_API("SetTimerQueueTimer", SetTimerQueueTimer_new),
	DECL_API("UnregisterWait", UnregisterWait_new),
	DECL_API("UnregisterWaitEx", UnregisterWaitEx_new),
/*** AUTOGENERATED APILIST NAMED EXPORTS END ***/
};

#if 0
static const apilib_unnamed_api kernel32_ordinal_apis[] =
{
/*** AUTOGENERATED APILIST ORDINAL EXPORTS BEGIN ***/
/*** AUTOGENERATED APILIST ORDINAL EXPORTS END ***/
};
#endif

const apilib_api_table apitable_kernel32 = DECL_TAB("KERNEL32.DLL", kernel32_named_apis, 0 /*kernel32_ordinal_apis*/);
