/*
 *  KernelEx
 *  Copyright (C) 2008, Xeno86
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifndef _COMDLG32_APILIST_H
#define _COMDLG32_APILIST_H

#include "kexcoresdk.h"
#include <commdlg.h>

BOOL init_comdlg32();
extern const apilib_api_table apitable_comdlg32;

/*** AUTOGENERATED APILIST DECLARATIONS BEGIN ***/
BOOL WINAPI GetOpenFileNameA_fix(LPOPENFILENAMEA lpofn);
BOOL WINAPI GetSaveFileNameA_fix(LPOPENFILENAMEA lpofn);
BOOL WINAPI GetSaveFileNameW_new(LPOPENFILENAMEW lpofn);
BOOL WINAPI GetOpenFileNameW_new(LPOPENFILENAMEW lpofn);
FWDPROC ChooseColorW_fwd;
FWDPROC ChooseFontW_fwd;
FWDPROC FindTextW_fwd;
FWDPROC GetFileTitleW_fwd;
FWDPROC PageSetupDlgW_fwd;
FWDPROC PrintDlgW_fwd;
FWDPROC ReplaceTextW_fwd;
/*** AUTOGENERATED APILIST DECLARATIONS END ***/

#endif
