all :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@

clean :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@

realclean :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@
