all :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C winsta $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@
    @$(MAKE) -C netapi32 $@

clean :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C winsta $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@
    @$(MAKE) -C netapi32 $@

realclean :
	@$(MAKE) -C msimg32 $@
	@$(MAKE) -C pdh $@
	@$(MAKE) -C winsta $@
	@$(MAKE) -C wtsapi32 $@
	@$(MAKE) -C uxtheme $@
	@$(MAKE) -C psapi $@
    @$(MAKE) -C netapi32 $@
