/*
 *  KernelEx
 *  Copyright (C) 2008, Ley0k
 *
 *  This file is part of KernelEx source code.
 *
 *  KernelEx is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published
 *  by the Free Software Foundation; version 2 of the License.
 *
 *  KernelEx is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 */

#ifndef _NETAPI32_APILIST_H
#define _NETAPI32_APILIST_H

#include "common.h"
#include <Lm.h>

BOOL init_netapi32();
extern const apilib_api_table apitable_netapi32;

/*** AUTOGENERATED APILIST DECLARATIONS BEGIN ***/
NET_API_STATUS WINAPI NetAlertRaise_new(LPCWSTR AlertEventName, LPVOID Buffer, DWORD BufferSize);
NET_API_STATUS WINAPI NetAlertRaiseEx_new(LPCWSTR AlertEventName, LPVOID VariableInfo, DWORD VariableInfoSize, LPCWSTR ServiceName);
NET_API_STATUS WINAPI NetApiBufferAllocate_new(DWORD ByteCount, LPVOID* Buffer);
NET_API_STATUS WINAPI NetApiBufferFree_new(LPVOID Buffer);
NET_API_STATUS WINAPI NetApiBufferReallocate_new(LPVOID OldBuffer, DWORD NewByteCount, LPVOID* NewBuffer);
NET_API_STATUS WINAPI NetApiBufferSize_new(LPVOID Buffer, LPDWORD ByteCount);
NET_API_STATUS NET_API_FUNCTION NetShareEnum_new(LMSTR servername, DWORD level, LPBYTE *bufptr, DWORD prefmaxlen, LPDWORD entriesread, LPDWORD totalentries, LPDWORD resume_handle);
NET_API_STATUS NET_API_FUNCTION NetUserGetInfo_new(LPCWSTR servername, LPCWSTR username, DWORD level, LPBYTE* bufptr);
/*** AUTOGENERATED APILIST DECLARATIONS END ***/

#endif
